security:
    providers:
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login: true

    access_control:
       - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/, roles: ROLE_ADMIN }
        # - { path: ^/adminroles: ROLE_ADMIN }
        # - { path: ^/profile roles: ROLE_USER }
        # - { path: ^/loginroles: IS_AUTHENTICATED_ANONYMOUSLY }
        #  - { path: ^/roles: ROLE_ADMIN }
